spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hellospringboot?serverTimezone=Asia/Seoul
    username: aplm12
    password: 123123
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver